//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyText
    {
        public DailyText()
        {
            this.DailyEdits = new HashSet<DailyEdit>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public System.DateTime PublicationDate { get; set; }
    
        public virtual ICollection<DailyEdit> DailyEdits { get; set; }
    }
}
