//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyEdit
    {
        public DailyEdit()
        {
            this.DailyCompares = new HashSet<DailyCompare>();
            this.DailyCompares1 = new HashSet<DailyCompare>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int DailyTextId { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.DateTimeOffset TimeTaken { get; set; }
        public string Result { get; set; }
    
        public virtual ICollection<DailyCompare> DailyCompares { get; set; }
        public virtual ICollection<DailyCompare> DailyCompares1 { get; set; }
        public virtual DailyText DailyText { get; set; }
        public virtual User User { get; set; }
    }
}
