//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InfostyleEntities : DbContext
    {
        public InfostyleEntities()
            : base("name=InfostyleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DailyCompare> DailyCompares { get; set; }
        public virtual DbSet<DailyEdit> DailyEdits { get; set; }
        public virtual DbSet<DailyText> DailyTexts { get; set; }
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<User_Tasks> User_Tasks { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
